#!/bin/sh

if [ -x "/etc/init.d/iptables" ]; then
  echo 'Add service boot configuration'
  update-rc.d iptables defaults >/dev/null || exit $?
  #invoke-rc.d iptables start || exit $?
  echo '####          README          ####'
  echo 'The first time start the service with "service iptables test"'
fi

exit 0
