#!/bin/sh

case "$1" in
purge|disappear)
  echo 'Remove configuration file'
  # Remove configuration
  rm -f /etc/default/iptables
  ;;
remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
  # nothing
  ;;
esac
echo 'Remove service boot configuration'
update-rc.d iptables remove >/dev/null

exit 0
